image: tapasco

variables:
  XILINXD_LICENSE_FILE: "/opt/cad/keys/xilinx"

before_script:
  - uname -a
  - ls
  - echo $SHELL
  - echo $PWD
  - source $PWD/setup.sh
  - export _JAVA_OPTIONS="-Dsbt.global.base=$TAPASCO_HOME/.sbt/ -Dsbt.ivy.home=$TAPASCO_HOME/.ivy2/ -Divy.home=$TAPASCO_HOME/.ivy2/"

stages:
  - toolchain-test
  - hls
  - import
  - compose
  - dse

scala-test:
  stage: toolchain-test
  script:
    # Execute your project's tests
    - sbt clean test

sbt-prepare:
  stage: toolchain-test
  artifacts:
      expire_in: 1 hrs
      untracked: true
  script:
    - sbt assembly
    - cd $TAPASCO_HOME/common/ip/tapasco_status && ./chiselSetup.sh

.hls-template: &hls-definition
  stage: hls
  dependencies:
    - sbt-prepare
  artifacts:
      untracked: true
      expire_in: 1 hrs
  script:
    - source /opt/cad/$VIVADO_OFFSET/settings64.sh
    - tapasco hls arraysum, arrayupdate

hls-2017.4:
  variables:
    VIVADO_VERSION: "2017.4"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *hls-definition

hls-2017.3:
  variables:
    VIVADO_VERSION: "2017.3"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *hls-definition

hls-2017.2:
  variables:
    VIVADO_VERSION: "2017.2"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *hls-definition

hls-2017.1:
  variables:
    VIVADO_VERSION: "2017.1"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *hls-definition

.import-template: &import-definition
  stage: import
  dependencies:
    - sbt-prepare
  script:
    - source /opt/cad/$VIVADO_OFFSET/settings64.sh
    - cd $TAPASCO_HOME/common/ip && zip -r precision_counter.zip precision_counter*
    - tapasco import $TAPASCO_HOME/common/ip/precision_counter.zip as 14

import-2017.4:
  variables:
    VIVADO_VERSION: "2017.4"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *import-definition

import-2017.3:
  variables:
    VIVADO_VERSION: "2017.3"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *import-definition

import-2017.2:
  variables:
    VIVADO_VERSION: "2017.2"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *import-definition

import-2017.1:
  variables:
    VIVADO_VERSION: "2017.1"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *import-definition

.compose-template: &compose-definition
  stage: compose
  script:
    - source /opt/cad/$VIVADO_OFFSET/settings64.sh
    - sdk install java
    - tapasco -v compose [arraysum x 1, arrayupdate x 1] @ 100 MHz

compose-2017.4:
  dependencies:
    - hls-2017.4
  variables:
    VIVADO_VERSION: "2017.4"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *compose-definition

compose-2017.3:
  dependencies:
    - hls-2017.3
  variables:
    VIVADO_VERSION: "2017.3"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *compose-definition

compose-2017.2:
  dependencies:
    - hls-2017.2
  variables:
    VIVADO_VERSION: "2017.2"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *compose-definition

compose-2017.1:
  dependencies:
    - hls-2017.1
  variables:
    VIVADO_VERSION: "2017.1"
    VIVADO_OFFSET: "xilinx/vivado/Vivado/$VIVADO_VERSION/"
  <<: *compose-definition
