image: centos:7

variables:
  XILINXD_LICENSE_FILE: "/opt/cad/keys/xilinx"

before_script:
  # Enable the usage of sources over https
  - uname -a
  - apt-get update -yqq
  - apt-get install apt-transport-https zip -yqq
  - apt-get install -y build-essential libgmp-dev libx11-dev libfontconfig-dev libxft-dev git python libc6-dev
  - ln -s /usr/lib/x86_64-linux-gnu/libgmp.so /usr/lib/x86_64-linux-gnu/libgmp.so.3
  # Install SBT
  - curl -s "https://get.sdkman.io" | bash
  - source "/root/.sdkman/bin/sdkman-init.sh"
  - sdk install sbt
  # Log the sbt version and TaPaSCo version
  - sbt sbtVersion version

stages:
  - toolchain-test
  - hls
  - compose
  - dse

scala-test:
  stage: toolchain-test
  script:
    # Execute your project's tests
    - source setup.sh
    - sbt clean test

.hls-template: &hls-definition
  stage: hls
  script:
    - source setup.sh
    - source /opt/cad/xilinx/vivado/Vivado/$VIVADO_VERSION/settings64.sh
    - sbt assembly
    - tapasco hls arraysum, arrayupdate

hls-2017.4:
  variables:
    VIVADO_VERSION: "2017.4"
  <<: *hls-definition

hls-2017.3:
  variables:
    VIVADO_VERSION: "2017.3"
  <<: *hls-definition

hls-2017.2:
  variables:
    VIVADO_VERSION: "2017.2"
  <<: *hls-definition

hls-2017.1:
  variables:
    VIVADO_VERSION: "2017.1"
  <<: *hls-definition

.compose-template: &compose-definition
  stage: compose
  script:
    - source setup.sh
    - source /opt/cad/xilinx/vivado/Vivado/$VIVADO_VERSION/settings64.sh
    - sbt assembly
    - tapasco compose [arraysum x 1, arrayupdate x 1] @ 100 MHz

compose-2017.4:
  variables:
    VIVADO_VERSION: "2017.4"
  <<: *compose-definition

compose-2017.3:
  variables:
    VIVADO_VERSION: "2017.3"
  <<: *compose-definition

compose-2017.2:
  variables:
    VIVADO_VERSION: "2017.2"
  <<: *compose-definition

compose-2017.1:
  variables:
    VIVADO_VERSION: "2017.1"
  <<: *compose-definition
