# This file is a template, and might need editing before it works on your project.
# Official Java image. Look for the different tagged releases at
# https://hub.docker.com/r/library/java/tags/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.
image: java:8

cache:
        paths:
                - .ivy2/

variables:
        SBT_OPTS: "-Divy.home=.ivy2/ -Dsbt.ivy.home=.ivy2/ -Xss16M"

before_script:
  # Enable the usage of sources over https
  - apt-get update -yqq
  - apt-get install apt-transport-https zip -yqq
  # Add keyserver for SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  # Install SBT
  - curl -s "https://get.sdkman.io" | bash
  - source "/root/.sdkman/bin/sdkman-init.sh"
  - sdk install sbt
  # Log the sbt version and TaPaSCo version
  - sbt sbtVersion version

test:
  script:
    # Execute your projects tests
    - ./chiselSetup.sh
    - sbt clean test
